### ISSUE TITLE
CIECAM02 color space

### ISSUE THREAD

**Issue by orionrush** [Evercoder/culori#108]
Hi Im looking for JS libs that implement CIECAM02 (ie not too many). As this project is new and quite exciting, I thought I'd ask if adding CIECAM02 was under consideration?

**Comment by orionrush** [comment]
Duplicate of #41

**Comment by danburzo** [comment]
Hi @orionrush, thanks for the kind words and sorry for the late reply. CIECAM02 and its derivatives are under consideration, as you identified in #41, although it's possible it's going to take a while, I'm afraid. I prefer to work from primary sources, and 2020 has not been too kind on the brainpower needed to tackle the material :P
