### ISSUE TITLE
[culori-names] Named colors and Nearest color

### ISSUE THREAD

**Issue by heinemannj** [Evercoder/culori#110]
I'm facing strange behaviours of the **named color** and  **nearest color function**.

A)
I only want's to have 2 nearest colors
"... Pass n = Infinity to get all colors in the array with a maximum distance of τ. ..."_

`SensorData[6]['MeasuredValue']=nearestNamedColors(culori.lab65(xyz65),2);`

At every time I get 3 colors output

B)
I really need a proper naming of colors (e.g. **Iodine-1**, **Iodine-2**, **Iodine-3**, ...
This results in errors

![image](https://user-images.githubusercontent.com/3251642/105845227-b9d22b80-5fda-11eb-977a-0edc1b1ba106.png)

**mycolors.js**
```
var IodineColorScale = {

	//CIE-L*a*b* coordinates of Iodine Color Index
	//
	//	'Iodine-1':	'100,  -3,  6',
	//	'Iodine-10':'100, -10, 50',

	// 1
	green:		'100,  -3,   6',
	//3
	yellow:		'100,  -7,  18',
	//5
	blue:		'100,  -9,  27',
	//7
	orange:		'100, -11,  37',
	//10
	red:		'100, -11,  59',
	//20
	grey:		'100, -10,  72',
	//90
	red:		'100,  20, 103'
};
```

**index.html**
```
<script src="https://cdn.jsdelivr.net/npm/culori@0.18.0/build/culori.umd.min.js"></script>
<script src="./mycolors.js"></script>

let colors = Object.keys(IodineColorScale);
let nearestNamedColors = culori.nearest(colors, culori.differenceCie76());
SensorData[6]['MeasuredValue']=nearestNamedColors(culori.lab65(xyz65),2);
```

Any help is appreatiated

**Comment by danburzo** [comment]
Hi @heinemannj! It seems you're basing your code from the API reference example:

```js
/*
	Get the three closest CSS named colors
 */

let colors = Object.keys(culori.colorsNamed);
let nearestNamedColors = culori.nearest(colors, culori.differenceCiede2000());

nearestNamedColors('lch(50% 70 60)', 3);
// => ["chocolate", "sienna", "peru"]
```

This example uses the [named CSS colors](https://en.wikipedia.org/wiki/Web_colors#Extended_colors), and it works because culori understands names like `chocolate` or `sienna` as color values. 

Given the structure of your `IodineColorScale`, let's see how we might implement what (I think) you're looking for. First of all, let's obtain an array of colors based on the Lab values, depending on what illuminant your values use, (D50 is `culori.lab`, D65 is `culori.lab65`): 

```js
let colors = Object.entries(IodineColorScale).map(entry => {
	let name = entry[0];
	let values = entry[1].split(/\s*,\s*/);
	let color = culori.lab65({
		l: +values[0],
		a: +values[1],
		b: +values[2]
	});

	return {
		name,
		color
	};
});
```

<details><summary>See how <code>colors</code> looks.</summary>

```json
[
  {
    "name": "green",
    "color": {
      "l": 100,
      "a": -3,
      "b": 6,
      "mode": "lab65"
    }
  },
  {
    "name": "yellow",
    "color": {
      "l": 100,
      "a": -7,
      "b": 18,
      "mode": "lab65"
    }
  },
  {
    "name": "blue",
    "color": {
      "l": 100,
      "a": -9,
      "b": 27,
      "mode": "lab65"
    }
  },
  {
    "name": "orange",
    "color": {
      "l": 100,
      "a": -11,
      "b": 37,
      "mode": "lab65"
    }
  },
  {
    "name": "red",
    "color": {
      "l": 100,
      "a": 20,
      "b": 103,
      "mode": "lab65"
    }
  },
  {
    "name": "grey",
    "color": {
      "l": 100,
      "a": -10,
      "b": 72,
      "mode": "lab65"
    }
  }
]
```

</details>

Now that we have our array `colors`, and assuming that `xyz65` holds a valid color, the code looks like this:

```js
let nearestIodine = culori.nearest(colors, culori.differenceCie76(), item => item.color);
SensorData[6]['MeasuredValue']=nearestIodine(xyz65, 2).map(item => item.name);
```

See that the third argument, called _accessor_ (and curiously underdocumented?), selects the color value from each item in the `colors` array. Then, after we compute the two nearest colors, I understand you need just their names, so we map the results to `item.name`. 

> Note: when using the `nearestIodine` function, you don't need to explicitly convert to the color to `lab65` to work, because when evaluating with `culori.differenceCie76()` they get converted to `lab65` under the hood.

Hope this helps!

**Comment by heinemannj** [comment]
First of all: **It Works** - Many Thanks!

![image](https://user-images.githubusercontent.com/3251642/105934871-428bae80-6051-11eb-9af5-c3b50167d89b.png)

Additional output of the minimum and maximum distance of τ would be helpful.
And finally I have to deal with ~15 different Color Index => A generic function make sense ...

For the other marked topics I will open seperate requests:

- Scaling for CIE-XYZ, CIE-xyY and RGB values
- Correlated Color Temperature (CCT)
- Dominant Wavelength

**mycolors.js**
```
// CIE-L*a*b* coordinates of Iodine Color Index
var IodineColorIndex = {
'IodineColor-1': '100, -3, 6',
'IodineColor-3': '100, -7, 18',
'IodineColor-5': '100, -9, 27',
'IodineColor-7': '100, -11, 37',
'IodineColor-10': '100, -11, 59',
'IodineColor-20': '100, -10, 72',
'IodineColor-90': '100, 20, 103'
};
```

**index.html**
```
<script src="https://cdn.jsdelivr.net/npm/culori@0.18.0/build/culori.umd.min.js"></script>
<script src="./mycolors.js"></script>

let IodineColors = Object.entries(IodineColorIndex).map(entry => {
	let name = entry[0];
	let values = entry[1].split(/\s*,\s*/);
	let color = culori.lab65({
		l: +values[0],
		a: +values[1],
		b: +values[2]
	});

	return {
		name,
		color
	};
});

let nearestIodineColors = culori.nearest(IodineColors, culori.differenceCie76(), item => item.color);
SensorData[6]['MeasuredValue'] = nearestIodineColors(xyz65, 2).map(item => item.name);
```

**Comment by heinemannj** [comment]
> A generic function make sense ...

Please review ;-)
Additional output of the minimum and maximum distance of τ would be helpful.

**mycolors.js**

```
// CIE-L*a*b* coordinates of Iodine Color Index
var IodineColorIndex = {
'IodineColor-1': '100, -3, 6',
'IodineColor-3': '100, -7, 18',
'IodineColor-5': '100, -9, 27',
'IodineColor-7': '100, -11, 37',
'IodineColor-10': '100, -11, 59',
'IodineColor-20': '100, -10, 72',
'IodineColor-90': '100, 20, 103'
};
```

**index.html**
`SensorData[6]['MeasuredValue'] = IndexColors(IodineColorIndex)(Sensor_XYZ, 2).map(item => item.name);`

```
function IndexColors(ColorIndex) {
	let ReferenceColors = Object.entries(ColorIndex).map(entry => {
		let name = entry[0];
		let values = entry[1].split(/\s*,\s*/);
		let color = culori.lab65({
			l: +values[0],
			a: +values[1],
			b: +values[2]
		});
		return {
			name,
			color
		};
	});
	let nearestReferenceColors = culori.nearest(ReferenceColors, culori.differenceCie76(), item => item.color);
	return nearestReferenceColors;
}
```

**Comment by danburzo** [comment]
>  Additional output of the minimum and maximum distance of τ would be helpful.

Do you mean something like this? 

```js
let colors = IndexColors(IodineColorIndex)(Sensor_XYZ, 2).map(color => ({
   ...color,
   distance: culori.differenceCie76()(Sensor_XYZ, color)
}));

let min_distance = Math.min(...colors.map(c => c.distance));
let max_distance = Math.max(...colors.map(c => c.distance));
```

I don't think this, or the `IndexColor` function, are general enough to warrant additions to the library API. culori strives for a compact set of features you can use to build your own functions, as needed.

**Comment by heinemannj** [comment]
Thanks to your support I was able to implement.
Again: Many thanks for your support!
