### ISSUE TITLE
hsla parsing incorrectly

### ISSUE THREAD

**Issue by tarngerine** [Evercoder/culori#118]
hi! love this library! thanks for all your hard work :)

ran into a bug — culori parses hsla (per https://www.w3.org/wiki/CSS3/Color/HSLA) expecting alpha to be 0-255, when the spec specifies 0-1, so other things like react-colorful provide an alpha value that culori incorrectly processes 

https://codesandbox.io/s/fervent-http-21ywl?file=/src/App.js

`hsla(219, 34%, 46%, 1)`
becomes 
`{"mode":"hsl","h":219,"s":0.34,"l":0.46,"alpha":0.00392156862745098}`
instead of 
`{"mode":"hsl","h":219,"s":0.34,"l":0.46,"alpha":1}`

**Comment by danburzo** [comment]
Thanks for the report, @tarngerine! Good catch, will fix in a sec.

**Comment by danburzo** [comment]
Fixed in `culori@0.18.2`.

**Comment by tarngerine** [comment]
wow! so fast. thank you!
