### ISSUE TITLE
Add CMY/CMYK color spaces

### ISSUE THREAD

**Issue by TimJentzsch** [Evercoder/culori#121]
https://en.wikipedia.org/wiki/CMYK_color_model

**Conversion from RGB to CMYK:**

K = 1 - max {R, G, B}
C = (1 - K - R) / (1 - K)  if K != 1 else 0
M = (1 - K - G) / (1 - K)  if K != 1 else 0
Y = (1 - K - B) / (1 - K)  if K != 1 else 0

**Comment by danburzo** [comment]
Hi @TimJentzsch, thank you for raising the issue. Unfortunately mapping an additive color space such as sRGB to a subtractive model is not straightforward and usually makes use of an ICC color profile that characterizes a specific CMYK device / print medium. The formula outlined above is [mentioned in the CSS Color Module 4 spec](https://drafts.csswg.org/css-color/#device-cmyk) as a fallback method that is unlikely to give a useful approximation. 

Including a new color space in culori comes with non-negligible overhead to the library size, and poses some challenges to some assumptions made in the code (namely, that color spaces have three, not four, channels). In my opinion this conversion code works better as an independent function implemented by the library user.
