### ISSUE TITLE
Color Interpolation test fails (on node v12.0.0+ on and Intel Based mac)

### ISSUE THREAD

**Issue by meodai** [Evercoder/culori#149]
```
    ✖ should be equivalent
    -----------------------
      operator: deepEqual
      expected: |-
        { mode: 'rgb', r: 0.25808621995139014, g: 0.37241162292636104, b: 0 }
      actual: |-
        { mode: 'rgb', r: 0.25808621995139025, g: 0.372411622926361, b: 0 }
      at: Test.<anonymous> (/Users/neodai/Sites/culori/test/interpolate.test.js:203:4)
      stack: |-
```

**Comment by meodai** [comment]
Its the only test that fails.
I'm on node v16.9.1 / osx 11.6

**Comment by danburzo** [comment]
I've tried running the tests in GitHub Actions, and [they pass](https://github.com/Evercoder/culori/actions/runs/1317523402) even with Node 16.9.1, and I can't reproduce the issue locally on macOS 11.6 (M1 processor) with that Node version installed... 

It's also bizarre in that `interpolate(['red', 'green'])(t0)` does not produce that color value for `t0 in [0, 0.1, 0.2, 0.5, 0.8, 1]`, which seems to be the value of `interpolate(['red', 0.2, 'green'])(0.5)`.

**Comment by meodai** [comment]
I am infinitely sorry for having wasted your time: this is the version I was actually testing: https://github.com/meodai/culori :( The updated version/tests pass just fine :(
