### ISSUE TITLE
Update `oklch` support

### ISSUE THREAD

**Issue by ai** [Evercoder/culori#167]
- [ ] `oklch()` can be used as a function without `color(--oklch, …)`.
- [ ] We should normalize `l` values between `oklch()` and `lch()`. Now `oklch()` uses `0-1`, but `lch()` uses `0-100`.

**Comment by danburzo** [comment]
Fixed in https://github.com/Evercoder/culori/pull/190. Note that `oklch()` and `oklab()` continue to use the `[0-1]` range as per latest spec.
