### ISSUE TITLE
XYB color space?

### ISSUE THREAD

**Issue by JobLeonard** [Evercoder/culori#188]
Last month the JPEG XL White Paper v2.0 was released:

https://ds.jpeg.org/whitepapers/jpeg-xl-whitepaper.pdf

From page six the paper:

> XYB colour space is an LMS-based colour model inspired by the human visual system, facilitating perceptually uniform quantization. It uses a gamma of 3 for computationally efficient decoding.

A footnote lists the formula for the sRGB -> XYB conversion:

![image](https://user-images.githubusercontent.com/259840/220081577-0fd3790e-d899-4d28-a8a6-3baa322108ed.png)

**Comment by danburzo** [comment]
Ah, nice! Thanks for this. I had noted a few implementations here (https://github.com/Evercoder/culori/discussions/178) but I'm glad there's a publicly-accessible formula.

**Comment by danburzo** [comment]
Added basic implementation in the PR above. Still needs documentation and test cases.

**Comment by danburzo** [comment]
Released as part of [`culori@2.1.0`](https://github.com/Evercoder/culori/releases/tag/v2.1.0).

**Comment by danburzo** [comment]
...and updated in [`culori@2.1.1`](https://github.com/Evercoder/culori/releases/tag/v2.1.1) to fix a detail I missed the first time around: that JPEG XL applies an additional _Chroma to luma_ adjustment, to which the only description (beyond probably the reference implementation) was Jon Sneyers' characterization as: <q>effectively subtracts Y from B</q>

**Comment by JobLeonard** [comment]
Huh, that's not cool. I'll send some feedback to him about that ("luckily" the interest in JXL is still niche enough that it's easy to reach the maintainers)
