### ISSUE TITLE
XYB: is the Chroma from Luma adjustment correction really in the JXL implementation?

### ISSUE THREAD

**Issue by facelessuser** [Evercoder/culori#200]
I was recently looking at this color space, and I can find any mention or implementation other than yours that implements XYB with the correction you do. I do believe it must have come from somewhere, but I cannot seem to find any reference except this one [youtube video](https://www.youtube.com/watch?v=rvhf6feXw7w). I was looking at the libjxl lib here and they do not seem to do it either: https://github.com/libjxl/libjxl/blob/main/lib/jxl/enc_xyb.cc#L74. Do you have a reference that contradicts this? Unfortunately, they do not seem to have any data sets to compare against.

**Comment by danburzo** [comment]
I couldn't really follow the libjxl repo, so I can't attest to what the code is doing. The Culori implementation follows the footnote in the [whitepaper](https://ds.jpeg.org/whitepapers/jpeg-xl-whitepaper.pdf) at page 6, which indeed does not capture the (default?) chroma-from-luma transform. The adjustment aims to bring the achromatic axis at X = B  = 0, and the author Jon Sneyers [calls it](https://twitter.com/jonsneyers/status/1605321352143331328) <q>the actual XYB space according to the final JPEG XL specification</q>. Unfortunately I don't have a non-social-media reference for it.

**Comment by facelessuser** [comment]
lol, well, I guess Twitter and Youtube are the references. I did see code in the reference related to chroma-from-luma about calculating the best configuration for the channels. And I agree it is difficult to follow. It seems it can be toggled, so I guess that is why they mention the "default".

I admit that the adjustment is a bit more lab-like and more intuitive. Thanks for your insight. I wanted to make sure I wasn't crazy.
