### ISSUE TITLE
Endless loop when using a double point

### ISSUE THREAD

**Issue by raidenmiro** [Evercoder/culori#204]
If you pass a value containing `..` to the `parse` function, for example `oklch(70% 0..1 156)`. there is an infinite loop, instead of return `undefined`.

**Comment by danburzo** [comment]
Thanks for reporting this, will check it out and publish a fix as soon as possible.

**Comment by danburzo** [comment]
Should be fixed in [`culori@3.1.1`](https://github.com/Evercoder/culori/releases/tag/v3.1.1).
