### ISSUE TITLE
bug: add missing exports for blerp and trilerp

### ISSUE THREAD

**Issue by prjctimg** [Evercoder/culori#233]
Hey, there @danburzo ! First of all thank you for the amazing library 👍🏽 

However, I'm having an issue with the imports. I am trying to import `blerp` and `trilerp` from the library using ESM syntax:

```js
import { blerp,trilerp } from 'culori'

// Gives an error in the editor => module has no exported member blerp or trilerp 

```

I've tried rebooting my pc and doing a reinstall both globally and locally from the NPM online registry with the `@latest` tag but still no luck.

```bash

npm i culori@latest & npm i culori@latest -g

```

How can I resolve this ? I've checked my `package.json` as well and I have `4.0.1` installed. I also went into the barrel module (index.js) for the library in the `node_modules` and saw that the functions are exported but still won't reflect in my files somehow. I'm using Node `v20.9.0` and npm `10.1.0`

Thanks in advance! 🚀

**Comment by danburzo** [comment]
Is the error just in your editor, or does the code fail to run/compile? Are you using TypeScript types? (those may be a bit out-of-date)

**Comment by prjctimg** [comment]
Yes, I have `@types/culori 2.1.0` definitions installed as a `devDependency` .

I even went a bit extreme last night 👀:

```bash

npm cache clean --force && rm -rf node_modules && rm -rf package-lock.json && npm i


```

After that I:


```bash

shutdown/r

```

to ensure that everything got a fresh start. 

If it's a TypeScript then I should have just `// @ts-nocheck` and plowed on. I didn't think of that 🤦🏾‍♂️

**Comment by danburzo** [comment]
Cool, glad that’s sorted out!
