### ISSUE TITLE
How do you get the same easing / gradient as the browser?

### ISSUE THREAD

**Issue by NullVoxPopuli** [Evercoder/culori#250]
For example, I have:
```css
background-image: linear-gradient(
  in oklch to right,
  var(--start),
  var(--end)
);
```

and then in javascript:
```js
const interpolator = interpolate([this.start, this.end], 'lch');
const colors = samples(5).map(interpolator);

return colors;
```

which generates something like this:
![image](https://github.com/user-attachments/assets/8e526dae-cf79-44de-9971-691e5203e2f6)

the color bands are obvious here -- but they should be pretty invisible, even though they are a couple rem wide.

the end-colors on the very left and very right are perfect, so it's the interpolation of the middle 3 colors that seems wrong.

Is there an existing easing function that matches the browser behavior?

I've deployed this here:
- https://19f56ef0.color-perception.pages.dev/configure?end=%23a51d2d&start=%231a5fb4

And my code is here:
- https://github.com/NullVoxPopuli/color-perception/pull/1/files#diff-bd2acdc10b373e98b305fd4f971c772b180fd06f177c8174c17a10fdfeae5504R77

**Comment by danburzo** [comment]
Hi @NullVoxPopuli, the problem might be produced by the fact that the browser gradient is in Oklch and the Culori JS code uses `lch` = CIELCH. Switching to `oklch` in `interpolate()` should give you a more consistent result.

**Comment by NullVoxPopuli** [comment]
thanks! ya, I forgot that oklch isn't lch.

I now an barely see my lines (as expected)

![image](https://github.com/user-attachments/assets/ae52362c-ff3c-4032-ae1e-9e87b6e3cae2)


thanks!

There is also a bit of an illusion, where, even though these lines are solid colors, they still look like they have gradients -- unless I turn my screen sideways.

![image](https://github.com/user-attachments/assets/a8dacc73-2616-4c55-a70d-7b61c5971d1c)

**Comment by danburzo** [comment]
> There is also a bit of an illusion, where, even though these lines are solid colors, they still look like they have gradients -- unless I turn my screen sideways.

I definitely see it!
