### ISSUE TITLE
CAM16 / CAT16 / CAM16-UCS

### ISSUE THREAD

**Issue by danburzo** [Evercoder/culori#41]
https://github.com/d3/d3-cam16
https://github.com/connorgr/d3-cam02
http://gramaz.io/d3-cam02/

**Comment by buddye** [comment]
I used the typescript port of colorio https://github.com/reinventing-wheels/cam16

colorio by Nico Schlömer who I believe published the cam16 fixes paper

**Comment by danburzo** [comment]
Awesome, thanks for the recommendations! The Nico Schlömer paper looks good.

**Comment by orionrush** [comment]
See also:
- https://github.com/baskerville/ciecam02

- https://github.com/eeeps/cam02-color-schemer
Built on Connor Gramazio’s implementation of CIECAM02 in D3

- https://observablehq.com/@jrus/cam16
A notebook implementation of the CAM16 color appearance model - author notes typos in Schlömer's paper:
https://github.com/nschloe/note-on-cam16/blob/gh-pages/main.pdf
