### ISSUE TITLE
Recipe: Math for obtaining a color at x% on a CSS linear gradient

### ISSUE THREAD

**Issue by danburzo** [Evercoder/culori#74]
Currently, culori can interpolate between evenly-spaced colors. However, in CSS you can define gradients by a set of colors and their offsets. It is useful, e.g. in [uiuiui](https://github.com/evercoder/uiuiui) for the (upcoming) gradient color picker, to be able to find out which color is at x% on such a gradient. Sounds like a mathy solution rather than something to add to the API, but a recipe for doing it would be interesting.

**Comment by danburzo** [comment]
On the other hand, we can implement this in `culori.interpolate` by sending an array of arrays:

```js
interpolate([
  ['red', 0],
  ['green', 0.2],
  ['blue', 0.8]
], 'lch')
```

**Comment by danburzo** [comment]
Re: color hints: https://github.com/w3c/csswg-drafts/issues/1332

**Comment by larathedev** [comment]
```
function interpolate(gradient, pos) {
	var color = 'rgba(0, 0, 0, 0)';
	for (var i = 1; i < gradient.stops.length; i++) {
		if (pos <= gradient.stops[i].offset && pos >= gradient.stops[i-1].offset) {
			
			color = Math.min(255, gradient.stops[i-1].color*(gradient.stops[i].offset - pos)/(gradient.stops[i].offset - gradient.stops[i-1].offset) +
					gradient.stops[i].color*(pos - gradient.stops[i-1].offset)/(gradient.stops[i].offset - gradient.stops[i-1].offset));
			//pseudocode, repeat the above for every channel for actual results
			
			break;
		}
	}
	return color;
}
```
